[package]
name = "sctd"
version = "0.1.0"
authors = ["Amir Saeid <amir@glgdgt.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
spa = { git = "https://github.com/amir/spa-rs", branch = "pub-SolarPos" }
clap = "2.33.0"

[dependencies.x11]
version = "2.18.2"
features = ["xlib", "xrandr"]
