[package]
name = "sctd"
version = "0.1.0"
authors = ["Amir Saeid <amir@glgdgt.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
spa = "0.2.0"

[dependencies.x11]
version = "2.18.2"
features = ["xlib", "xrandr"]
